version: 2.1
jobs:
  build:
    docker:
    -  image: circleci/python:3.9
    steps:
      - checkout
      - run:
          command: |
            mkdir venv
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python training.py