version: 2.1
jobs:
  build:
    docker:
    -  image: circleci/python:3.9
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            python training.py
  test:
    steps:
      - run:
          command: |
            python evaluate.py